### PR TITLE
DataChannelRewriter2 without shared buffer

### PR DESCRIPTION
**Pull request by JakubVanek**
Reworked variant of https://github.com/ev3dev-lang-java/ev3dev-lang-java/commit/7bd73bcfb31a824ed6f4f6c253bd01881b593bb8

### CODE REVIEW

**Comment by jabrena** [comment]
Can you add UnitTest for the alternative?

**Comment by JakubVanek** [comment]
> Can you add UnitTest for the alternative?

There are no unit tests for DataChannelRewriter v1, so I cannot port them to this variant.

>  What is the value in compare to the previous Writer?

It handles thread safety in a different way - it avoids sharing the internal buffer in the first place instead of relying on `synchronized`.

**Comment by jabrena** [comment]
> There are no unit tests for DataChannelRewriter v1, so I cannot port them to this variant.

I missed it in the PR, arrggh Oki

**Comment by jabrena** [comment]
Old proposal

**Pull request closed without merging**
