### PR TITLE
Simplify Docker testing integration

### PR DESCRIPTION
**Pull request by JakubVanek**
- simplifies & moves file copying from docker.gradle to Dockerfile
 - removes dockerRun task
 - adds task descriptions

### CODE REVIEW

**Comment by jabrena** [comment]
Hi @JakubVanek,

how to run the tests with the new **Gradle** tasks?

Maybe now, we are not using that feature in travis:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/master/.travis.yml

https://travis-ci.org/ev3dev-lang-java/ev3dev-lang-java/builds/473438000

**Comment by JakubVanek** [comment]
Hi,

the `dockerTest` task remains the way how to run the tests.

I'm not sure if using it on Travis has an advantage - we already have a `openjdk-10` defined in there. Using Docker on top of it would add another delay - it would have to download the appropriate docker containers.

Thanks,

Jakub

**Comment by jabrena** [comment]
Testing in local the branch

**Comment by jabrena** [comment]
In local with Linux, run this process:

@JakubVanek, 

do you know how to fix the issue in Linux?

```
jabrena@roslaptop:~/IdeaProjects/ev3dev-lang-java$ ./gradlew dockerTest

> Task :dockerBuild
Sending build context to Docker daemon 152.5 MB

Step 1/5 : FROM openjdk:10-jdk-slim
 ---> 02f0ec2751d2
Step 2/5 : COPY ./ /home/gradle/build/
 ---> 891ea715640a
Removing intermediate container 607f7bf528a6
Step 3/5 : RUN cd /home/gradle/build/ && rm -rf $(cat .gitignore)
 ---> Running in 90656e2e7704
 ---> b77db1e67787
Removing intermediate container 90656e2e7704
Step 4/5 : WORKDIR /home/gradle/build/
 ---> e0f9f7365dc8
Removing intermediate container f4dede54d059
Step 5/5 : CMD bash
 ---> Running in 42ee42033c32
 ---> 51fe8799572d
Removing intermediate container 42ee42033c32
Successfully built 51fe8799572d

> Task :dockerTest
Downloading https://services.gradle.org/distributions/gradle-4.7-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:221)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:657)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

> Task :dockerTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerTest'.
> Process 'command 'docker'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
2 actionable tasks: 2 executed

```

But in travis run nice.
https://travis-ci.org/ev3dev-lang-java/ev3dev-lang-java/builds/475334181

**Comment by jabrena** [comment]
It is a local configuration issue. In Travis, it is running.
Merging

**Comment by JakubVanek** [comment]
I found that this can be caused when DNS is configured to use local resolver (on Ubuntu it is typical for NetworkManager):
* https://github.com/moby/moby/issues/541
* https://stackoverflow.com/a/39400887

**Pull request merged**
