### PR TITLE
#653

### PR DESCRIPTION
**Pull request by JakubVanek**

### CODE REVIEW

**Comment by JakubVanek** [comment]
Tested:
```java
package issues;

import ev3dev.actuators.lego.motors.EV3LargeRegulatedMotor;
import lejos.hardware.port.MotorPort;

public class Issue654 {
    public static void main(String[] args) {
        EV3LargeRegulatedMotor m = new EV3LargeRegulatedMotor(MotorPort.C);
        m.setSpeed(360);
        m.rotate(360);
        m.stop();
    }
}
```
The underlying `BaseRegulatedMotor` and `EV3DevDevice` use all the changed methods.

**Comment by JakubVanek** [comment]
This is mostly refactoring and some overhead avoidance (no `PrintWriter` etc.). Code for checking is in previous comment.

**Comment by jabrena** [comment]
This PR, it is better if we split in micro PR... to avoid long discussions... logging, method to method

**Comment by JakubVanek** [comment]
I do not want to invest more effort into this, so this PR should probably be closed.

**Pull request closed without merging**
