### PR TITLE
Feature/#518

### PR DESCRIPTION
**Pull request by mingan666**
Fix for brickPi3 and Raspberry Pi 3 B+. Also fixes some gradle issues for OpenJdk10.

### CODE REVIEW

**Comment by jabrena** [comment]
Hi @mingan666, I merged the PR.

I like so much your work with the file `build.gradle`. It was necessary anyway, I suspect that current version is possible to be refactored a bit more.

I added `Lombok` dependency which it was missed.

I am thinking to create a repository for testing purposes. The idea could be to create some examples to tests with the physical device. 

Do you have to time to test BrickPi with some sensors and Motors please?

Cheers

Juan Antonio

**Comment by mingan666** [comment]
If you'd create a repository with tests for target system that would be great. I will run them on my hardware.

**Comment by mingan666** [comment]
I also had a look at your lombok fix. Is it really needed?
Have a look at patch [Refactored build.gradle for openjdk-10](https://github.com/ev3dev-lang-java/ev3dev-lang-java/pull/526/commits/1fd213936bc96871bf747a3b5c59e1863a5b36c4)

Those lines caused issues when using openJdk10 in my development as the annotationProcessor does not seem to work anymore. Instead I changed to using the gradle-lombok plugin to accomplish the same. Also, now we point to 2 different lombok versions: line 46 (version = '1.18.2') and line 56-58 (lombok:1.16.20).

As I wrote in that particular comment, I did test the new solution with both java 8 and java 10... Please check it out once more :)

**Comment by mingan666** [comment]
I did not really recall what happens in which case... But I reset my local branch to before my changes for the lombok issue and got the following issue:

```
shark:~/git/ev3dev-lang-java$ gradle test
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.ExceptionInInitializerError

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
shark:~/git/ev3dev-lang-java$
```

As you can see, the issue I'm trying to show you is not related to IntelliJ. It's when running gradle from the cmd line. In this example its on the linux subsystem and simular problems exists when running gradle within IntelliJ. Just for clarity: this happens only when changing from jdk8 to openjdk10 during the gradle build.

These issues are resolved by changing to the gradle-lombok plugin.

```
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.1 (Oracle Corporation 10.0.1+10-Ubuntu-3ubuntu1)
OS:           Linux 4.4.0-17134-Microsoft amd64
```

**Comment by mingan666** [comment]
Also I need to be able run the tests from the linux subsystem since some of the test cases do not play well with windows. The fake ev3dev path seems to contain illegal characters for windows.

`java.nio.file.InvalidPathException: Illegal char <:> at index......`

**Comment by jabrena** [comment]
Sorry I didn´t want to annoy you @mingan666 :)

I am trying to test in local with the same configuration than you.

In my idea, I was compiling with Java 8, but by command line I executed the tests with Java 10. 
I am configuring IntelliJ with OpenJDK 10.

Give me a hour to have the same scenario than you.

One moment :)

**Comment by jabrena** [comment]
Hi @mingan666,

I am using `OSX`, to replicate your scenario, I upgraded my `IntelliJ CE` to version 2018.2. later I installed Oracle OpenJDK10 with Brew. Previously I installed from brew OpenJDK10 from AdoptOpenJDK 10 but for some reason, I could not set that Installation as a valid JDK inside of IntelliJ so, now I have latest IntelliJ with latest JVM from Oracle. :)

When I opened IntelliJ, I imported the project and I replicated your scenario, IntelliJ doesn´t recognise LOGGER object. 

To solve it, I enabled "Annotation processors" and `Lombok plugin` on IntelliJ. With that settings I could execute tests from IntelliJ context menu and by terminal.

This explanation is better for you?

Juan Antonio

**Comment by jabrena** [comment]
In relation to the `fake ev3dev`, I developed on OSX and tested on Linux with Travis and I didn´t have any problem. Maybe exist the problem that you say, we could fix it :)

**Comment by jabrena** [comment]
Tell me if you fixed your local issue.

In my computer and in Travis CI with latest commit:

``` 
Commit:
b9c6cf53a5741244dcb00c965a287d78082ba5f7 [b9c6cf5]
```

I can compile and execute the tests.

Good night from Spain

Cheers

Juan Antonio

**Comment by mingan666** [comment]
Not really... For me it also works fine to run the tests from intellij, but it should be possible to run from the cmd-line also right?

Just to be clear... what version of ev3dev-lang-java are you testing? To get to the issue, make sure you are on version prior to my fix called 'Refactored build.gradle for openjdk-10'. Then go to a **terminal** and write 'gradle test'. Alternative, open the gradle window in intellij (for me its in the right panel in intellij) and run test task from there.

To solve that problem (after a lot of googling...) I figured the correct way to use later versions of lombok together with gradle is as I did it in my patch; e.g. changing from the annotationProcessor to using the gradle-lombok plugin. 

**Now we mix both options, which doesn't seem good to me....**

See also https://projectlombok.org/setup/gradle. The plugin seems to be the recommended way.

**Comment by mingan666** [comment]
I don't see a simple solution for the 'fake ev3dev' problem. It fake path must match the path on the target system and it seems to be using the colon (:) in some cases. This is not a valid character in a windows path so it will not be allowed.

Its not a problem for me, as long as I can run the tests from the cmd line using the linux subsystem (a windows 10 app running linux on top of windows).

**Comment by jabrena** [comment]
Hi @mingan666,

I am testing in local with you branch #518 and latest commit (Your patch). Previously, maybe I was testing with OpenJDK 8 and this is the reason to not have that behaviour.

I followed your comment and I disabled "Annotation processor" and I Uninstalled "Lombok Plugin". Finally I restarted the IDE and from the contextual menu and from the terminal everything run fine.

Many thanks for this conversation :)

**Comment by mingan666** [comment]
Just to be sure... you still need the lombok plugin in intellij - this makes the normal intellij testing possible.

the gradle plugin is just fixing it for gradle runs...

**Comment by jabrena** [comment]
mmm, I am testing with IDEA menu and from the idea terminal and everything goes fine from my side.

**Comment by jabrena** [comment]
In relation to the question about paths, now I understand your comment.

If you observe in the file: `jessie:properties` you will see some path with that problem:

`ev3.led.left.red=/sys/class/leds/ev3:left:red:ev3dev/brightness`

This is a path designed for a Linux environment (EV3Dev) so as you say, possible developers for this library should code on Linux or OSX. Another workaround, is the usage of the Docker container which we have and we use for Travis:

```
 ./gradlew clean dockerTest
```

**Comment by mingan666** [comment]
I didn't realize that we still haven't come to an understanding regarding the build.gradle file until I turned of my computer yesterday...

I deliberately removed the following lines (the manual way of configuring lombok): 
```
    annotationProcessor("org.projectlombok:lombok:1.18.2")
    compileOnly("org.projectlombok:lombok:1.18.2")
    testCompileOnly("org.projectlombok:lombok:1.18.2")
```

since they are obsolete since I replaced them with these lines (the plugin way):
```
plugins {
    id 'io.franzbecker.gradle-lombok' version '1.14'
}

lombok {
    version = '1.18.2'
    sha256 = ""
}
```

Now you have added them back, which means there are now mixing these two ways of configuring the dependencies, which is never a good idea...

Now, what I wondered yesterday  was if you had run into any problem causing you to add them back? My changes worked on both windows and linux and with both jdk8 and openjdk10....

**Comment by jabrena** [comment]
Good morning @mingan666, 

This morning, I read your last comment and I understood your idea. I removed the dependency in the way that I was used to add for Lombok and it run nice but in the IntelliJ, I observe that in the class `BaseElement.java` appear the line:

`LOGGER.info("Reset EV3Dev testing infrastructure");`

In red so, I suppose that although now, the compilation is ok with the way that you introduced, I appreciate it, we should use the Lombok plugin from IntelliJ point of view to disappear that side effect from the code visualization, the execution by contextual menu and by terminal was fixed.

What is your opinion?

Juan Antonio

**Comment by mingan666** [comment]
That's about right.

For the gradle task/cmd line, the updated gradle.build file works as intended.
For Intellij nothing has changed, it still needs the specific lombok configuration exactly as before.

**Comment by jabrena** [comment]
What is your `Full Name`?

I would like to add you in the file:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/develop/CONTRIBUTORS.md

Juan Antonio

**Pull request merged**
