### PR TITLE
#651

### PR DESCRIPTION
**Pull request by JakubVanek**
This implements the proposed write-if-different solution. Also, to actually make use of it, it uses `auto` mode for tacho motors.

### CODE REVIEW

**Comment by JakubVanek** [comment]
I have now noticed that other platforms really do not work with `auto` mode. http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-stretch/motors.html#motor-autodetect So now auto mode is used only on EV3.

**Comment by JakubVanek** [comment]
The timeout issue can actually be reproduced with a medium motor on EV3 on the 2.3.4 kernel.
Code is in issue #663: https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/663#issuecomment-494510420
```
2019-05-21 20:45:33 [main] ERROR ev3dev.utils.Sysfs - File: '/sys/class/tacho-motor/motor3/command' without write permissions.
Exception in thread "main" java.lang.RuntimeException: Operation not executed: /sys/class/tacho-motor/motor3/command with value reset
	at ev3dev.hardware.EV3DevDevice.setStringAttribute(EV3DevDevice.java:118)
	at ev3dev.actuators.lego.motors.BaseRegulatedMotor.<init>(BaseRegulatedMotor.java:95)
	at ev3dev.actuators.lego.motors.EV3MediumRegulatedMotor.<init>(EV3MediumRegulatedMotor.java:26)
	at issues.Issue663.main(Issue663.java:8)
```

**Comment by JakubVanek** [comment]
Tested on `4.14.117-ev3dev-2.3.4-ev3` kernel on EV3. Other platforms shouldn't be affected. They also use the write-if-different solution now, but they are still using `TACHO_MOTOR` mode and not the `AUTO_MODE`.
```java
package issues;

import ev3dev.actuators.lego.motors.EV3MediumRegulatedMotor;
import lejos.hardware.port.MotorPort;

public class Issue663 {
    public static void main(String[] args) throws Exception {
        EV3MediumRegulatedMotor m = new EV3MediumRegulatedMotor(MotorPort.D);
        m.resetTachoCount();
        int dstAngle = 90;
        for (int i = 0; i < 10; i++) {
            m.rotateTo(dstAngle);
            dstAngle = -dstAngle;
            Thread.sleep(1000);
        }
    }
}
```

Before the fix, with 300 MHz CPU clock and a medium motor in port D, this crashes on the first iteration. With the fix, all ten iterations succeed.

**Comment by JakubVanek** [comment]
This PR makes the BaseRegulatedMotor delay less necessary - it avoids the udev asynchronous process if the port is already in the correct mode. This can be felt the most on the EV3 platform.

The crashes were worked around by increasing the delay to 1000ms, however I have done it only in the `BaseRegulatedMotor` and not in `BasicMotor`.

**Comment by JakubVanek** [comment]
Rejected by weighing testing difficulty

**Comment by jabrena** [comment]
Rejected

**Pull request closed without merging**
