### PR TITLE
LED enum and documentation

### PR DESCRIPTION
**Pull request by wuqs-net**
Hello, 

I have made some changes to the `EV3Led` class. Here are the changes that have been made:

- Change the constructor to use enum to indicate direction instead of integers. The old constructor is kept but documented as deprecated.
- Remove some unnecessary declaration and if checks to clean the code up a little bit.
- Complete the documentation for the class and methods.
- Modify the `EV3LedTest` class so that it can test the new methods.

I'm also planning on adding more features to it such as setting the RG colour (since there's no blue) of the light and getting the current status, and probably the blinking lights mentioned in the documentation but not implemented yet.

Regards,

Keisun

### CODE REVIEW

**Comment by JakubVanek** [comment]
Tested on kernel `4.14.117-ev3dev-2.3.4-ev3`.
```java
package issues;

import ev3dev.actuators.ev3.EV3Led;
import lejos.utility.Delay;

public class Issue659 {

    public static void main(String[] args) {
        EV3Led ledL = new EV3Led(EV3Led.Direction.LEFT);
        EV3Led ledR = new EV3Led(EV3Led.Direction.RIGHT);

        ledL.setPattern(0);
        ledR.setPattern(0);
        Delay.msDelay(1000);

        go(ledL, 1);
        go(ledL, 2);
        go(ledL, 3);
        go(ledL, 0);
        go(ledR, 1);
        go(ledR, 2);
        go(ledR, 3);
        go(ledR, 0);
    }

    private static void go(EV3Led led, int pattern) {
        led.setPattern(pattern);
        Delay.msDelay(1000);
    }

}
```

**Comment by jabrena** [comment]
Hi @wuqs-net, many thanks for the PR.

I will review the PR soon and changes, but anyway many thanks

**Comment by jabrena** [comment]
Hi @wuqs-net,

I was reviewing the initial example:

``` java
@Slf4j
public class LEDExample {

    /**
     * @param args
     */
    public static void main(String[] args) {

        LOGGER.info("Example using EV3 Led");

        LED led = new EV3Led(EV3Led.LEFT);
        led.setPattern(0);
        Delay.msDelay(1000);
        led.setPattern(1);
        Delay.msDelay(1000);
        led.setPattern(2);
        Delay.msDelay(1000);
        led.setPattern(3);
        Delay.msDelay(1000);
        led.setPattern(0);

        LED led2 = new EV3Led(EV3Led.RIGHT);
        led2.setPattern(0);
        Delay.msDelay(1000);
        led2.setPattern(1);
        Delay.msDelay(1000);
        led2.setPattern(2);
        Delay.msDelay(1000);
        led2.setPattern(3);
        Delay.msDelay(1000);
        led2.setPattern(0);
    }

}
``` 

and you are right, current implementation use an Integer in the constructor.

``` 
public static final int LEFT = 0;
public static final int RIGHT = 1;


public EV3Led(final int button) {

}
```

You are right, the implementation based on Enum is better.

**Comment by jabrena** [comment]
Testing the example from @JakubVanek 

```java
import ev3dev.actuators.ev3.EV3Led;
import lejos.utility.Delay;

public class Issue659 {

    public static void main(String[] args) {
        EV3Led ledL = new EV3Led(EV3Led.Direction.LEFT);
        EV3Led ledR = new EV3Led(EV3Led.Direction.RIGHT);

        ledL.setPattern(0);
        ledR.setPattern(0);
        Delay.msDelay(1000);

        go(ledL, 1);
        go(ledL, 2);
        go(ledL, 3);
        go(ledL, 0);
        go(ledR, 1);
        go(ledR, 2);
        go(ledR, 3);
        go(ledR, 0);
    }

    private static void go(EV3Led led, int pattern) {
        led.setPattern(pattern);
        Delay.msDelay(1000);
    }

}
```

**Comment by jabrena** [comment]
Working fine both examples on `Debian Stretch`.

Merging the PR

**Comment by jabrena** [comment]
I will add you in the document: 
https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/master/CONTRIBUTORS.md

In the next release.

**Comment by wuqs-net** [comment]
Thank you for merging the PR!

**Comment by jabrena** [comment]
Thanks you, and welcome.

This week, more PRs!

Cheers

**Pull request merged**
